version: '3.4'

services:
  appointmentmicroserviceapi:
    image: appointment:latest
    container_name: appointmentmicroserviceapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 53212
    ports:
      - 53212:53212
    depends_on:
      - mysql
      - gatewayapi
    volumes:
      - appointmentmicroserviceapi:/app/sql


  gatewayapi:
    image: gateway:latest
    container_name: gatewayapi
    restart: on-failure
    networks:
      - demo
    ports:
      - 54689:54689
    depends_on:
      - react

  searchmicroserviceapi:
    image: search:latest
    container_name: searchmicroserviceapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 53174      
    ports:
      - 53174:53174
    depends_on:
      - mysql
      - gatewayapi
    volumes:
      - searchmicroserviceapi:/app/sql

  feedbackmicroserviceapi:
    image: feedback:latest
    container_name: feedbackmicroserviceapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 8080      
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - gatewayapi
    volumes:
      - feedbackmicroserviceapi:/app/sql


  usermicroserviceapi:
    image: user:latest
    container_name: usermicroserviceapi
    restart: on-failure
    networks:
      - demo
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: mysql
      DATABASE_SCHEMA: MYSQLHealtcareDB
      DATABASE_PORT: 3306
      PORT: 53236      
    ports:
      - 53236:53236
    depends_on:
      - mysql
      - gatewayapi
    volumes:
      - usermicroserviceapi:/app/sql

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    restart: always
    networks:
      - demo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: MYSQLHealtcareDB
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  react:
    image: react:latest
    container_name: react
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:        
      - webAppClientapp:/react/src
      - '/react/node_modules'


volumes:
  gatewayapi:
  usermicroserviceapi:
  feedbackmicroserviceapi:
  searchmicroserviceapi:
  appointmentmicroserviceapi:
  mysql-data:
  webAppClientapp:

networks:
  demo:
    name: demo
    driver: bridge
