version: '3.4'

services:
  appointmentmicroserviceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  feedbackmicroserviceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  gatewayapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  searchmicroserviceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  usermicroserviceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

